[giscus]
  enabled = true
  repo = "beaudrychase/beaudrychase.github.io"
  repoID = "R_kgDOJHFunQ"
  category = "Announcements"
  categoryID = "DIC_kwDOJHFunc4CgenG"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  lang = "en"
  
  [[social_media.items]]
    enabled = true
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/beaudrychase'

  [[social_media.items]]
    enabled = true
    title = 'LinkedIn'
    icon = 'brand-linkedin'
    link = 'https://www.linkedin.com/in/beaudry-chase/'