baseURL = "https://beaudrychase.github.io"
title = "Dev Log by Beaudry Chase"
author = "Beaudry Chase"
copyright = "Beaudry Chase"
languageCode = "en-us"
buildFuture = true
buildDrafts = false
pagination.pagerSize = 12

DefaultContentLanguage = 'en'
defaultContentLanguage = 'en'
pluralizelisttitles = 'false'

refLinksErrorLevel = 'WARNING'
refLinksNotFoundURL = '/'

timeout = 60000

rssLimit = 3

enableInlineShortcodes = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser.attribute]
    block = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'onesenterprise'
    tabWidth = 4

[permalinks]
  posts = '/:year/:month/:slugorcontentbasename/'
  categories = '/:slug/'

[params]
  author = 'Beaudry Chase'
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).



[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 1
  [[menu.main]]
    identifier = 'blog'
    name = 'blog'
    url = '/blog/'
    weight = 2

[taxonomies]
  author = 'authors'
  tag = 'tags'
  category = 'categories'
  translator = 'translators'
  lang = 'languages'
[languages]
  [languages.en]
    languageName = 'English'
    weight = 1

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = 'tags'
    weight = 100
  [[related.indices]]
    name = 'lang'
    weight = 80
